[package]
name = "qix"
version = "0.1.0"
authors = ["Jonathan Rowlands"]

[dependencies]
# amethyst = "*"
amethyst = {git="https://github.com/amethyst/amethyst.git", branch="develop"}

nalgebra = "0.11.0"
ncollide = "0.11.0"
